<html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Uso de Librerías y Funciones</title>
</head>

<body>
<?php
function CabeceraPagina() {
    ?>
    <FONT SIZE="+1">Esta cabecera estará en todas sus páginas.</FONT><BR>
    <hr> 
    <?php
}

function PiePagina() {
    ?>
    <hr>
    <FONT SIZE="-1">Este es el pie de página.</FONT><BR>
    Autor: Laura Guadalupe López Piñón
    <?php
}
?>

</body>
</html>